### ISSUE TITLE
Query for image data 

### ISSUE THREAD

**Issue by taoqi98** [styxsys0927/Med-MMHL#1]
Dear Authors,

Thank you for your effort in releasing this medical disinformation detection dataset, which is highly helpful for facilitating the research in this field. When I attempt to access the data via the link you provided in Dropbox, however, I found that the image data for the data in ``image_article" is not provided. Could you help give a link for downloading the corresponding image data?

Best

**Comment by styxsys0927** [comment]
Hi taoqi98,

Thank you for being interested in our dataset! We must miss the image data while migrating the files from Google Drive to Dropbox... Just uploaded a .zip file containing the images. Please let us know if there are any other issues.

Yanshen

**Comment by taoqi98** [comment]
I can access the image data via the link. Thanks a lot!
